version: "3.9"
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: .
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/creditsea
      - CLIENT_ORIGIN=http://localhost:5173
      - MAX_UPLOAD_MB=5
      - NODE_ENV=production
    ports:
      - "4000:4000"
    depends_on:
      - mongo
volumes:
  mongo_data:
